version: "3.3"
services:

  client:
    build: ./client
    depends_on:
      - server
    ports:
      - 3000:3000
    environment:
      SERVER: "http://127.0.0.1:8080"
      CLIENT: "http://127.0.0.1:3000"
      # OAuth2
      GOOGLE_OAUTH_SECRET: "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"
      GOOGLE_OAUTH_API_KEY: "656903528628-sn7o1btc0ac4jo87jt5nvm7vrhs73rp4.apps.googleusercontent.com"

  db:
    restart: always
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      # Server
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8080"
      # DB
      POSTGRES_DB: user #DB name
      POSTGRES_HOST: db #DB service name
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      # WeatherAPI
      WEATHER_API_KEY: 20fdd92ad15e47869a1140527210112
      # OAuth2
      GOOGLE_OAUTH_SECRET: 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
      GOOGLE_OAUTH_API_KEY: 656903528628-sn7o1btc0ac4jo87jt5nvm7vrhs73rp4.apps.googleusercontent.com